Updated requirements.txt with latest versions
treeverse/lakeFS-hooks pull request #6
Opened 2022-09-21 14:40 UTC by vinodhini8694

2022-09-22 06:24 UTC, nopcoder requested changes

2022-09-22 06:24 UTC, nopcoder commented on requirements.txt
> +jinja2<3.1.2
The code doesn't use jinja

2022-09-22 21:01 UTC, vinodhini8694 commented on requirements.txt
> +jinja2<3.1.2
This is the error I got without jinja:

Traceback (most recent call last):
  File "/usr/local/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/usr/local/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.9/site-packages/jinja2/__init__.py)

2022-09-26 21:38 UTC, vinodhini8694 commented on requirements.txt
> +jinja2<3.1.2
@nopcoder  Was able to run hooks server without jinja. Updated the requirements.txt

2022-09-27 02:42 UTC, nopcoder commented on requirements.txt
> +jinja2<3.1.2
Flask got a list of dependencies (https://flask.palletsprojects.com/en/latest/installation/). But these will be installed as part of it's requirements, not ours.

2022-09-27 02:42 UTC, nopcoder approved these changes
lgtm!

2022-09-27 02:50 UTC, merged